### ISSUE TITLE
"Frequently Asked Questions" page or section?

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling-website#16]
People are actively asking [questions](https://github.com/gosling-lang/gosling.js/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) about Gosling.js, and we can update our website to help future users find the proper information before asking. 

While some descriptions can be added directly to existing pages of the documentation, some of them do not seem to have good-fitting sections or pages. We could probably create a "Frequently Asked Questions" page or section and provide those descriptions.

Such examples include, but not limited to, 

- How to debug gosling specs? (https://github.com/gosling-lang/gosling.js/issues/551#issuecomment-943428272)
- Tooltips are hidden under another component (https://github.com/gosling-lang/gosling.js/issues/528)
- Visualization is rendered, but hidden (https://github.com/gosling-lang/gosling.js/issues/534#issuecomment-937715972)
- How to make Gosling visualization responsive? (https://github.com/gosling-lang/gosling.js/issues/528#issuecomment-943199059)

**Comment by wangqianwen0418** [comment]
Sounds great! I will create an FQA section below the docs tab
