### ISSUE TITLE
URL of gist-based spec in Getting Started not working

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling-website#34]
- URL: https://gosling.js.org/?gist=flekschas/e6e388332814886d4d714efd0e88093b
- Page: http://gosling-lang.org/docs/

**Comment by wangqianwen0418** [comment]
Thanks for reporting this issue! 
I have updated the gist example to fix it  https://github.com/gosling-lang/gosling-website/commit/962bed0bbd77993f4f1cea35d8f4bda447a53e34.
