### ISSUE TITLE
Add a ISMB tutorial page

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling-website#39]
We can add an ISMB tutorial page that includes details about the tutorial (e.g., motivation, schedules, presenters) that are in our proposal. We can use this page to advertise our tutorial on Tweet.

Reference: https://zitniklab.hms.harvard.edu/biomedgraphml/
Our proposal: https://docs.google.com/document/d/1n-3qB43HoUuVuspH7uAFUGUGRrELcK2A0zow6kkb1Kk/edit?usp=sharing

**Comment by sehilyi** [comment]
Maybe the page link can be displayed under the current `Tutorials` page (http://gosling-lang.org/tutorials/):

![Screen Shot 2022-02-03 at 10 59 49](https://user-images.githubusercontent.com/9922882/152379546-40a7056b-42a6-41d6-a84e-c5422963066b.png)

**Comment by wangqianwen0418** [comment]
Good idea! 
I will work on it soon

**Comment by sehilyi** [comment]
Thanks a lot!
