### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling-website#5]
In the dark mode, 

- Some parts of the website become difficult to read (e.g., "Get Started" on the home page and "Tips" on the public data page). We can update styles to make them more readable.
- Code blocks become visually too highlighted. Perhaps, use a dark theme in the browser's dark mode?

**Screenshots**:
![Screen Shot 2021-05-13 at 11 34 21 AM](https://user-images.githubusercontent.com/9922882/118149059-30a30100-b3df-11eb-942e-d5493d46b0c1.png)

![Screen Shot 2021-05-13 at 11 33 40 AM](https://user-images.githubusercontent.com/9922882/118149085-37ca0f00-b3df-11eb-8f31-4409ac3a7c10.png)

![Screen Shot 2021-05-13 at 11 27 25 AM](https://user-images.githubusercontent.com/9922882/118148644-c4c09880-b3de-11eb-86ba-2dd59d426518.png)

**Comment by wangqianwen0418** [comment]
I disabled the dark mode for the website and will close this issue for now
