### ISSUE TITLE
VCF data support is missing

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling-website#56]
We need to add a description of VCF data support (`v0.9.19`) which is currently missing in the `Data` page (http://gosling-lang.org/docs/data).

Definition in Gosling.js:

https://github.com/gosling-lang/gosling.js/blob/9f921168b62ebe32eade019e1438ca755110c238/src/core/gosling.schema.ts#L1029

**Comment by wangqianwen0418** [comment]
No problem, will add it soon. One quick question, does VCF data require HiGlass server?

**Comment by sehilyi** [comment]
Thanks! It does not use a HiGlass server.
